<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <name>Spring Cloud Stream Tracer AMPS</name>
    <description>Official Open Source library by FinDev team.</description>
    <url>https://fin.dev</url>

    <licenses>
        <license>
            <name>The MIT License (MIT)</name>
            <url>https://opensource.org/licenses/MIT</url>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>findev-tech</id>
            <name>FinDev Team</name>
            <email>robot@fin.dev</email>
            <organization>FinDev</organization>
            <organizationUrl>https://fin.dev</organizationUrl>
        </developer>
    </developers>

    <scm>
        <connection>scm:git:git://github.com/FindevGlobal/spring-cloud-stream-amps.git</connection>
        <developerConnection>scm:git:ssh://github.com:FindevGlobal/spring-cloud-stream-amps.git</developerConnection>
        <url>https://github.com/FindevGlobal/spring-cloud-stream-amps</url>
    </scm>

    <parent>
        <groupId>com.findevglobal</groupId>
        <artifactId>spring-cloud-stream-amps</artifactId>
        <version>1.1.0</version>
    </parent>

    <artifactId>spring-cloud-stream-tracer-amps</artifactId>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <opentracing.version>0.33.0</opentracing.version>
        <micrometer.version>1.0.12</micrometer.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>com.findevglobal</groupId>
            <artifactId>spring-cloud-stream-binder-amps</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing-bridge-brave</artifactId>
            <version>${micrometer.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>io.opentracing</groupId>
            <artifactId>opentracing-api</artifactId>
            <version>${opentracing.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>io.opentracing</groupId>
            <artifactId>opentracing-util</artifactId>
            <version>${opentracing.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <version>${spring.version}</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>junit</groupId>
                    <artifactId>junit</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>io.opentracing</groupId>
            <artifactId>opentracing-mock</artifactId>
            <version>${opentracing.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>